# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='\xc2ge')),
                ('date', models.DateTimeField(auto_now=True, verbose_name="Date d'inscription")),
                ('profil_picture_signed', models.FileField(blank=True, null=True, upload_to='users/avatars/sign_language', verbose_name='Photo de profil sign\xe9e')),
                ('profil_picture', models.FileField(blank=True, null=True, upload_to='users/avatars/image', verbose_name='Photo de profil')),
                ('newsletter', models.BooleanField(default=False, help_text="Je souhaite recevoir l'actualit\xe9 du site internet")),
                ('description_signed', models.FileField(blank=True, null=True, upload_to='users/description/', verbose_name='Description sign\xe9e')),
                ('description', models.TextField(help_text='D\xe9crivez-vous bri\xe8vement, vos hobbies, votre exp\xe9rience... si vous le souhaitez', null=True, verbose_name='Description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
