# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(help_text="Apparaitra dans l'adresse du site", max_length=100)),
                ('contenu', models.TextField(null=True, verbose_name='Contenu')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Utilisateur', verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categorie')),
            ],
        ),
    ]
