# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Utilisateur', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text="Apparaitra dans l'adresse du site", max_length=100, unique=True),
        ),
    ]
